apiVersion: v1
kind: Pod
metadata:
  name: dog-class-pod
spec:
  containers:
  - name: dog-class
    image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    ports:
    - containerPort: 80
  restartPolicy: Never
