name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Docker image build & push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
        env:
          DEBUG: true

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Update kubeconfig with EKS cluster credentials
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        env:
          IMAGE_NAME: pamirova/dog_class
          IMAGE_TAG: ${{ steps.timestamp.outputs.timestamp }}
        run: |
          kubectl apply -f ai/dog.yaml
