name: Unit test & app validation

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install PyTorch and torchvision
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.0.0 torchvision==0.15.1

      - name: Install pytest
        run: |
          pip install pytest

      - name: Run Pytest
        run: |
          pytest ai/test.py

      - name: Run the code
        run: |
          python ai/dog_class.py
